### ISSUE TITLE
tree.toStringTree() failed at empty context

### ISSUE THREAD

**Issue by jszheng** [antlr/antlr4-python3#27]
with g4 file
```antlr
grammar CSV;

top : hdr row+ ;
hdr : row ;

row : field (',' field)* '\r'? '\n' ;

field
    :   TEXT	# text
    |   STRING	# string
    |   	    # empty
    ;

TEXT : ~[,\n\r"]+ ;
STRING : '"' ('""'|~'"')* '"' ;
```

```
% cat t.csv
Details,Month,Amount
Mid Bonus,June,"$2,000"
,January,"""zippo"""
Total Bonuses,"","$5,000"

% pygrun CSV top --tree t.csv
Traceback (most recent call last):
  File "D:\work\antlr4\bin\pygrun", line 162, in <module>
    process(input_stream, class_lexer, class_parser)
  File "D:\work\antlr4\bin\pygrun", line 143, in process
    lisp_tree_str = parser_ret.toStringTree(recog=parser)
  File "D:\Apps\Python\Python34\lib\site-packages\antlr4\RuleContext.py", line 185, in toStringTree
    return Trees.toStringTree(self, ruleNames=ruleNames, recog=recog)
  File "D:\Apps\Python\Python34\lib\site-packages\antlr4\tree\Trees.py", line 61, in toStringTree
    buf.write(cls.toStringTree(t.getChild(i), ruleNames))
  File "D:\Apps\Python\Python34\lib\site-packages\antlr4\tree\Trees.py", line 61, in toStringTree
    buf.write(cls.toStringTree(t.getChild(i), ruleNames))
  File "D:\Apps\Python\Python34\lib\site-packages\antlr4\tree\Trees.py", line 52, in toStringTree
    if t.getChildCount()==0:
  File "D:\Apps\Python\Python34\lib\site-packages\antlr4\ParserRuleContext.py", line 177, in getChildCount
    return len(self.children)
TypeError: object of type 'NoneType' has no len()
```

It seems like the empty alternative in the field generate a NoneType that the toStringTree can not handle.

**Comment by ericvergnaud** [comment]
already fixed, see latest code
