### ISSUE TITLE
AttributeError: readonly attribute when calling parser starting rule

### ISSUE THREAD

**Issue by zevektor** [antlr/antlr4-python3#45]
I get the following error when I try to parse a file.
For some reason i.start in IntervalSet.py cannot be written.
I am using anaconda3 on OSX Yosemite.

```
Traceback (most recent call last):
  File "/Users/alessandro/PycharmProjects/PyCodeSensor/codeexploration/csvexporter.py", line 39, in <module>
    main(sys.argv)
  File "/Users/alessandro/PycharmProjects/PyCodeSensor/codeexploration/csvexporter.py", line 34, in main
    doparsing(argv)
  File "/Users/alessandro/PycharmProjects/PyCodeSensor/codeexploration/csvexporter.py", line 29, in doparsing
    tree = parser.code()
  File "/Users/alessandro/PycharmProjects/PyCodeSensor/parser/CPPGrammarParser.py", line 931, in code
    self._errHandler.sync(self)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/error/ErrorStrategy.py", line 235, in sync
    if la==Token.EOF or la in recognizer.atn.nextTokens(s):
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/atn/ATN.py", line 91, in nextTokens
    return self.nextTokensNoContext(s)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/atn/ATN.py", line 85, in nextTokensNoContext
    s.nextTokenWithinRule = self.nextTokensInContext(s, None)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/atn/ATN.py", line 77, in nextTokensInContext
    return anal.LOOK(s, ctx=ctx)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/LL1Analyzer.py", line 101, in LOOK
    self._LOOK(s, stopState, lookContext, r, set(), set(), seeThruPreds, True)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/LL1Analyzer.py", line 189, in _LOOK
    self._LOOK(t.target, stopState, ctx, look, lookBusy, calledRuleStack, seeThruPreds, addEOF)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/LL1Analyzer.py", line 189, in _LOOK
    self._LOOK(t.target, stopState, ctx, look, lookBusy, calledRuleStack, seeThruPreds, addEOF)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/LL1Analyzer.py", line 180, in _LOOK
    self._LOOK(t.target, stopState, newContext, look, lookBusy, calledRuleStack, seeThruPreds, addEOF)

 File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/LL1Analyzer.py", line 189, in _LOOK
    self._LOOK(t.target, stopState, ctx, look, lookBusy, calledRuleStack, seeThruPreds, addEOF)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/LL1Analyzer.py", line 189, in _LOOK
    self._LOOK(t.target, stopState, ctx, look, lookBusy, calledRuleStack, seeThruPreds, addEOF)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/LL1Analyzer.py", line 180, in _LOOK
    self._LOOK(t.target, stopState, newContext, look, lookBusy, calledRuleStack, seeThruPreds, addEOF)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/LL1Analyzer.py", line 189, in _LOOK
    self._LOOK(t.target, stopState, ctx, look, lookBusy, calledRuleStack, seeThruPreds, addEOF)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/LL1Analyzer.py", line 196, in _LOOK
    set_ = set_.complement(Token.MIN_USER_TOKEN_TYPE, self.atn.maxTokenType)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/IntervalSet.py", line 80, in complement
    result.removeRange(i)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/IntervalSet.py", line 100, in removeRange
    self.removeOne(v.start)
  File "/Users/alessandro/anaconda/lib/python3.4/site-packages/antlr4/IntervalSet.py", line 147, in removeOne
    i.start = v + 1
AttributeError: readonly attribute
```

**Comment by ericvergnaud** [comment]
Hi
Sorry but I won't be able to look into this before week after next
Eric

Envoyé de mon iPhone

**Comment by ericvergnaud** [comment]
Hi,
can you try replacing the line
i.start = v + 1
by
self.intervals[k] = range(v+1, i.stop)

**Comment by ericvergnaud** [comment]
also can you provide a minimal grammar that triggers that behavior so we can use it in our test suite

**Comment by ericvergnaud** [comment]
Hi,
closing this in the absence of response.
Eric
